{% set version = "2.6.0" %}

package:
  name: robotframework-tidy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/robotframework-tidy/robotframework-tidy-{{ version }}.tar.gz
  sha256: 4d51bca73150871731a4a742f3239d32d58418ddb572970002bae7f4668a986d

build:
  number: 0
  noarch: python
  entry_points:
    - robotidy=robotidy.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - click >=7.0
    - colorama >=0.4.3
    - packaging >=21.0
    - pathspec >=0.9.0,<0.10.0
    - python >=3.7
    - rich-click >=1.3
    - robotframework >=4.0
    - tomli >=2.0.0

test:
  imports:
    - robotidy
  commands:
    - pip check
    - robotidy --help
  requires:
    - pip

about:
  home: https://github.com/MarketSquare/robotframework-tidy
  summary: Code autoformatter for Robot Framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
