{% set version = "1.6.1" %}

package:
  name: robotframework-tidy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/robotframework-tidy/robotframework-tidy-{{ version }}.tar.gz
  sha256: 016a64ad6e8c44fb923d9e3811c47af0e56340a7e9e01df6695309f9a3fec193

build:
  number: 0
  noarch: python
  entry_points:
    - robotidy=robotidy.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - click >=7.0
    - colorama >=0.4.3
    - pathspec ==0.9.0
    - python >=3.7
    - robotframework >=4.0
    - toml >=0.10.2

test:
  imports:
    - robotidy
  commands:
    - pip check
    - robotidy --help
  requires:
    - pip

about:
  home: https://github.com/MarketSquare/robotframework-tidy
  summary: Code autoformatter for Robot Framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
