{% set version = "2.1.1" %}

package:
  name: robotframework-tidy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/robotframework-tidy/robotframework-tidy-{{ version }}.tar.gz
  sha256: 4abaef014f625e46e1fc1a7280d12a71ae94ec17a65938adcd5df09877be32f3

build:
  number: 0
  noarch: python
  entry_points:
    - robotidy=robotidy.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - click >=7.0
    - colorama >=0.4.3
    - packaging
    - pathspec >=0.9.0,<0.10.0
    - python >=3.7
    - robotframework >=4.0
    - toml >=0.10.2

test:
  imports:
    - robotidy
  commands:
    - pip check
    - robotidy --help
  requires:
    - pip

about:
  home: https://github.com/MarketSquare/robotframework-tidy
  summary: Code autoformatter for Robot Framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
